FROM ubuntu:precise

MAINTAINER Brandon Burton <brandon@inatree.org>
ENV BUILD_DIR /usr/local/build
RUN mkdir $BUILD_DIR
ADD scripts/* $BUILD_DIR/
WORKDIR $BUILD_DIR
RUN chmod +x build.rb
RUN bundle install
RUN bundle exec build.rb

ENTRYPOINT ["/bin/true"]
