FROM solarce/dotfiles-ubuntu-precise:latest

MAINTAINER Brandon Burton <brandon@inatree.org>

ENV BUILD_DIR /home/ubuntu/build
ENV DEBIAN_FRONTEND noninteractive
USER ubuntu
RUN mkdir $BUILD_DIR
ADD scripts/* $BUILD_DIR/
ADD packages $BUILD_DIR/packages
RUN ls $BUILD_DIR

WORKDIR $BUILD_DIR
RUN chmod +x build.rb
RUN bundle install
RUN bundle exec ./build.rb
